blank_issues_enabled: false
contact_links:
  - name: ST Community Forum
    url: https://community.st.com/s/
    about: Be a part of ST Community !
  - name: ST Support Center
    url: https://my.st.com/ols#/ols/
    about: For communication and support.
