on: [push]

jobs:
  my_test:
    runs-on: ubuntu-latest
    name: codespell and artistic style run
    steps:
    - name: codespell and artistic style run
      id: cs_as
      uses: embalbe/activity_test@master
      with:
        codespell_list: 'codespell.pippo'
        astyle_cfg: 'astyle.pluto'
    # Use the output from the `hello` step
    - name: Get the results
      run: echo "test 002 print results ${{ steps.cs_as.outputs.results }}"