on: [push]

jobs:
  my_test:
    runs-on: ubuntu-latest
    name: codespell and artistic style
    steps:
    - name: code spell
      id: codespell
      uses: embalbe/activity_test/action_001@master
      with:
        repo: 'https://github.com/embalbe/stdc_cpy.git'
        codespell_list: './.github/workflows/codespell.cfg'
        astyle_cfg: 'SKIP'
    - name: artistic style
      id: astyle
      uses: embalbe/activity_test/action_001@master
      with:
        repo: 'https://github.com/embalbe/stdc_cpy.git'
        codespell_list: 'SKIP'
        astyle_cfg: './.github/workflows/astyle.cfg'
    # Use the output from the `hello` step
    - name: Get the results
      run: echo "test 022 print results ${{ steps.codespell.outputs.results }} \r"
           echo "test 022 print results ${{ steps.astyle.outputs.results }}"
