on: [push]

jobs:
  my_test:
    runs-on: ubuntu-latest
    name: codespell and artistic style run
    steps:
    - name: codespell
      id: codespell
      uses: embalbe/activity_test@master
      with:
        codespell_list: 'codespell.pippo'
        astyle_cfg: 'NONE'
    - name: artistic style
      id: astyle
      uses: embalbe/activity_test@master
      with:
        codespell_list: 'NONE'
        astyle_cfg: 'astyle.pluto'
    # Use the output from the `hello` step
    - name: Get the results
      run: echo "test 003 print results ${{ steps.codespell.outputs.results }}"
      run: echo "test 003 print results ${{ steps.astyle.outputs.results }}"